// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQrR5Iig5_U2MA_HHgKyq8pgn8-IJcZVg',
    appId: '1:808331321792:web:7c7bd9ccce558f4eca2825',
    messagingSenderId: '808331321792',
    projectId: 'interview-prep-buddy-1e370',
    authDomain: 'interview-prep-buddy-1e370.firebaseapp.com',
    storageBucket: 'interview-prep-buddy-1e370.firebasestorage.app',
    measurementId: 'G-XHN4E27Y26',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBhPEiOSLCISTbB1Wx9Ur7V0dQbuZfXiU',
    appId: '1:808331321792:android:5a68de530fb00d2bca2825',
    messagingSenderId: '808331321792',
    projectId: 'interview-prep-buddy-1e370',
    storageBucket: 'interview-prep-buddy-1e370.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmfdr65TBjUsZ5I9rxvaXTrgUss0bJQOE',
    appId: '1:808331321792:ios:4facf833f5ec5d15ca2825',
    messagingSenderId: '808331321792',
    projectId: 'interview-prep-buddy-1e370',
    storageBucket: 'interview-prep-buddy-1e370.firebasestorage.app',
    iosBundleId: 'com.example.interviewPrepBuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmfdr65TBjUsZ5I9rxvaXTrgUss0bJQOE',
    appId: '1:808331321792:ios:4facf833f5ec5d15ca2825',
    messagingSenderId: '808331321792',
    projectId: 'interview-prep-buddy-1e370',
    storageBucket: 'interview-prep-buddy-1e370.firebasestorage.app',
    iosBundleId: 'com.example.interviewPrepBuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQrR5Iig5_U2MA_HHgKyq8pgn8-IJcZVg',
    appId: '1:808331321792:web:a5a4ef27510eb3d4ca2825',
    messagingSenderId: '808331321792',
    projectId: 'interview-prep-buddy-1e370',
    authDomain: 'interview-prep-buddy-1e370.firebaseapp.com',
    storageBucket: 'interview-prep-buddy-1e370.firebasestorage.app',
    measurementId: 'G-JKK195Q7Z6',
  );
}
